# Generated by Django 4.1.3 on 2022-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAMStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.PositiveIntegerField(max_length=50, verbose_name='Used Memory Status')),
                ('free', models.PositiveIntegerField(max_length=50, verbose_name='Free Memory Status')),
                ('total', models.PositiveIntegerField(max_length=50, verbose_name='Total Memory Status')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Report Created')),
            ],
            options={
                'verbose_name': 'RAM Status',
                'verbose_name_plural': 'RAM Statuses',
            },
        ),
    ]
