# Generated by Django 4.1.3 on 2022-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramstatus',
            name='free',
            field=models.FloatField(max_length=50, verbose_name='Free Memory Status'),
        ),
        migrations.AlterField(
            model_name='ramstatus',
            name='total',
            field=models.FloatField(max_length=50, verbose_name='Total Memory Status'),
        ),
        migrations.AlterField(
            model_name='ramstatus',
            name='used',
            field=models.FloatField(max_length=50, verbose_name='Used Memory Status'),
        ),
    ]
