# Generated by Django 4.1.3 on 2022-11-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_ramstatus_free_alter_ramstatus_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramstatus',
            name='free',
            field=models.FloatField(max_length=50, verbose_name='Free Memory Status(MB)'),
        ),
        migrations.AlterField(
            model_name='ramstatus',
            name='report_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Report Created'),
        ),
        migrations.AlterField(
            model_name='ramstatus',
            name='total',
            field=models.FloatField(max_length=50, verbose_name='Total Memory Status(MB)'),
        ),
        migrations.AlterField(
            model_name='ramstatus',
            name='used',
            field=models.FloatField(max_length=50, verbose_name='Used Memory Status(MB)'),
        ),
    ]
