# Generated by Django 4.1.3 on 2022-11-03 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_ramstatus_free_alter_ramstatus_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramstatus',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 3, 56, 59, 433557), verbose_name='Report Created'),
        ),
    ]
